### ISSUE TITLE
Update Ruby extension in VSCode

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#1002]
https://github.com/bigbinary/wheel/blob/c118239933b64a377e4e9c618bc747a38d8640bc/.vscode/extensions.json#L5

^ Please do a global search to find other places where necessary changes ought to be made. We have to update the .vscode folder of `granite` repo similarly.

@navaneethsdk _a We need to remove this extension as it has been deprecated in favor of https://github.com/Shopify/vscode-ruby-lsp.  The transition is smooth - we just need to uninstall current extension and the install the new one and then add the following to the end of the User Settings(JSON) file:
```json
  "[ruby]": {
    "editor.defaultFormatter": "Shopify.ruby-lsp",
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.insertSpaces": true,
    "files.insertFinalNewline": true,
    "editor.semanticHighlighting.enabled": true
  },
```

Make necessary changes in LRRB as well as neetoEngineering KB articles.

PS: If you already have some settings in your local `.vscode` folder within the project, then that ought to be updated with above mentioned settings.

**Comment by yedhink** [comment]
@anmol-kumar0815 Can we prevent neeto-git from adding the `manual-qa` label in Wheel? If yes, please take care of it.

**Comment by anmol-kumar0815** [comment]
@yedhink Done, updated configuration for `Wheel` repo.

**Comment by navaneethsdk** [comment]
@anmol-kumar0815 I believe the same is applicable to the granite repo as well: https://github.com/bigbinary/granite/issues?q=is%3Aissue+is%3Aclosed+label%3Amanual-qa-needed

**Comment by anmol-kumar0815** [comment]
@navaneethsdk Done, Update config for granite repo as well.
