### ISSUE TITLE
Remove docker files

### ISSUE THREAD

**Issue by sritabh** [bigbinary/wheel#1028]
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/690
@sritabh _a

**Comment by sritabh** [comment]
@yedhink _a Are we planning to keep [Using docker for development](https://github.com/bigbinary/wheel/blob/main/docs/using_docker.md) option and hence should the file related to docker needed to be kept?

**Comment by yedhink** [comment]
@sritabh _a Let's maintain the file. Please upgrade the docker image and verify docker is working as intended locally. You can contact Ghouse if you need latest image.

**Comment by sritabh** [comment]
> Let's maintain the file. Please upgrade the docker image and verify docker is working as intended locally. You can contact Ghouse if you need latest image.

The above will be tracked in the issue https://github.com/bigbinary/wheel/issues/1030
Closing this issue.
