### ISSUE TITLE
Verify development using docker 

### ISSUE THREAD

**Issue by sritabh** [bigbinary/wheel#1030]
Ref: https://github.com/bigbinary/wheel/issues/1028#issuecomment-2002933074
@sritabh _a

**Comment by sumanranjanpanda** [comment]
@sritabh Do we need to maintain Docker in the wheel?

**Comment by sritabh** [comment]
As per the discussion in the standup this will be taken up in the next milestone to verify the development setup using docker
cc: @sandip-mane
