### ISSUE TITLE
Upgrade Ruby to 3.2.4 and fix failing `bin/setup`

### ISSUE THREAD

**Issue by vivek-viswam-rv** [bigbinary/wheel#1033]
https://monosnap.com/file/eVVcSZe928R1XSL5f7mAYcDCs1Zsnd

cc: @yedhink 

bug _t

**Comment by yedhink** [comment]
@jaimysimon _a Minor issue. Let's also upgrade the Ruby version to 3.2.4 https://github.com/bigbinary/wheel/blob/main/.ruby-version
