### ISSUE TITLE
Use Rails template

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/wheel#121]
Rails added http://guides.rubyonrails.org/rails_application_templates.html to help build things are like wheel. We should be using it.

@kalamkar _a When you are on bench then start working on it.

**Comment by kalamkar** [comment]
@neerajdotname _a 

We may need to copy files like assets, controllers, models etc. from `wheel` repo to the new application using DSL method `run`. Is it fine OR shall I write code like follows to generate each file using template code.

```
file 'app/components/foo.rb', <<-CODE
  class Foo
  end
CODE
```

**Comment by neerajdotname** [comment]
@kalamkar I think we can copy assets, models, controllers etc.

**Comment by neerajdotname** [comment]
@ershad _a

**Comment by ershad** [comment]
@neerajdotname _a I was going through `suspenders` gem and template API documentation, looks like that approach is not a good choice for Wheel. In Wheel, we have many files other than the ones which Rails provides by default. For example, we have 10 controllers excluding `application_controller.rb`, 3 models and many view files. If we are to write a template file or a generator gem, we need to organise these files and have to make sure all the files are copied in correct locations. Instead, it's much simpler and easy to update if we can keep Wheel as a basic Rails app, which can be cloned to make new projects.

Template API is helpful when we need to replace Gemfile or to configure a few settings/initializers in a new Rails app. For app generators like `suspenders`, they use `Rails::Generators` with a lot of custom code, which I think will be difficult to maintain. Eg:

https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/generators/app_generator.rb
https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/app_builder.rb

This is how they organise the files:

https://github.com/thoughtbot/suspenders/tree/master/templates

Am I missing anything? Would you like to proceed in this direction?

**Comment by neerajdotname** [comment]
ok then lets drop it.

I was afraid that by not running rails new we might miss out something.
