### ISSUE TITLE
Upgrade to rails 5.1

### ISSUE THREAD

**Issue by rkr090** [bigbinary/wheel#161]
Blocked by:

https://github.com/activeadmin/inherited_resources/pull/433
https://github.com/collectiveidea/delayed_job_active_record/pull/134
https://github.com/plataformatec/devise/issues/4518

**Comment by bknarendra** [comment]
Blocked on 

- [ ] (https://github.com/plataformatec/devise/issues/4518)
- [ ] (https://github.com/activeadmin/inherited_resources/pull/433)
- [ ] (https://github.com/collectiveidea/delayed_job_active_record/pull/134)
- [ ] (https://github.com/plataformatec/simple_form/pull/1487))

**Comment by neerajdotname** [comment]
@bknarendra Can you check if there is any progress on any of the three open issues.

**Comment by bknarendra** [comment]
@neerajdotname I will look into it tomorrow

**Comment by bknarendra** [comment]
@neerajdotname It seems delayed_job_active_record issue is still open others have added support for rails 5.1

**Comment by neerajdotname** [comment]
@bknarendra Version 4.1.2 was released a few hours ago. Can you see if we can upgrade this wheel app to Rails 5.1 before you go on vacation? If you are tied up with numberf work then let us know.

**Comment by neerajdotname** [comment]
@akshay-vishnoi Can you take a look at this issue.

**Comment by bknarendra** [comment]
@neerajdotname Looking into it

**Comment by bknarendra** [comment]
@neerajdotname Closing the PR as its already taken care in #163
