### ISSUE TITLE
Default to Sidekiq

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/wheel#182]
We use it in mostly all of our projects over DJ. We should default to what we actually use.
It also have doesn't have a hard deployment strategy for Heroku, etc.

https://github.com/mperham/sidekiq/wiki/Deployment

**Comment by neerajdotname** [comment]
The purpose is to make it easy to quickly test something. Maintaining redis server takes more work and  it does go down a lot. I get so many notifications from heroku related to redis automatically going down and then going up then I had to filter them and delete them.

Right now I'm in the middle of dealing with automatic records deletion in "apisnapshot". There I need a simple job to delete old records. DJ is perfect for that. 

wheel needs to be lowest common denominator. If we agree on that then we should stick with DJ.

**Comment by vipulnsward** [comment]
I see it a bit differently, I have seen a couple of times we have a task to "migrate" to Sidekiq in new projects because that's what clients and even others prefer now.

Sidekiq being more popular and having more support than DJ is also one of the reasons many want to default to sidekiq and has a wider support.

Just something to factor in when deciding our default, instead of repeating the task of moving to Sidekiq in new projects.

**Comment by vipulnsward** [comment]
@neerajdotname wanted to revisit this, more and more we change DJ to sidekiq as a project matures.

Doing this in advance will save us from this extra cost in a matured project.

**Comment by neerajdotname** [comment]
Yes let's do this.
