### ISSUE TITLE
Change default ids to uuid 

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/wheel#200]
https://blog.bigbinary.com/2016/04/04/rails-5-provides-application-config-to-use-uuid-as-primary-key

Since all our projects inherit wheel, this is becoming a chore. We should not use plain ids anymore in projects.

**Comment by neerajdotname** [comment]
@hari816 _a Can you work on this.

**Comment by neerajdotname** [comment]
@Rohann7 _a

**Comment by neerajdotname** [comment]
@Rohann7 Are you working on it.

**Comment by Rohann7** [comment]
Yes, I’m working on it.
