### ISSUE TITLE
Nightly builds?

### ISSUE THREAD

**Issue by sharang-d** [bigbinary/wheel#208]
@neerajdotname Can we revert [the commit which disabled nightly builds](https://github.com/bigbinary/wheel/commit/af8c61e563a1503e44a21453c00bee131c6df642)?

The [reason for setting up nightly builds](https://github.com/bigbinary/wheel/pull/173#issue-157568383) in the first place was to discover CVEs and fix them which would otherwise go unnoticed.
Some examples of commits which were pushed because of these nightly builds:
https://github.com/bigbinary/wheel/commit/c6a8165f34aced46d73a0638835926c4cbf9ec48
https://github.com/bigbinary/wheel/commit/a09a1b865d6975512dc29ecb0c1b1a5857e26f40
https://github.com/bigbinary/wheel/commit/31a5f92939951c3edf7a1866bd5f04aff9067069
https://github.com/bigbinary/wheel/commit/11cc604006d51bf0aae78c1e63fc34cc1d57dca1

The current build takes ~1:30 minutes to complete which I think we can spare every day for this purpose. 

Let me know what you think.

**Comment by neerajdotname** [comment]
@sharang-d _a Sure go ahead and send another PR to revert it.
