### ISSUE TITLE
Fix CI build

### ISSUE THREAD

**Issue by sharang-d** [bigbinary/wheel#263]
https://circleci.com/gh/bigbinary/wheel/1480

```
error /home/circleci/wheel/node_modules/node-sass: Command failed.
Exit code: 1
```
`yarn install` seems to be producing this error.

Idk when I'd be able to get to it. If anyone can pick it up please do.

**Comment by ashiksp** [comment]
@sharang-d  I will have a look at this.

**Comment by ashiksp** [comment]
Some of the links I have made references:
https://github.com/sass/node-sass/issues/2447
https://github.com/yarnpkg/yarn/issues/3485
https://github.com/yarnpkg/yarn/issues/4867

**Comment by ashiksp** [comment]
node-saas version used is [4.11.0](https://github.com/sass/node-sass/releases/tag/v4.11.0), which has node support environment till node version 11. The [failed builds](https://circleci.com/gh/bigbinary/wheel/1486) are using node version `v12.13.0`. This is causing issues here.

**Comment by neerajdotname** [comment]
@ashiksp Can you send a PR with the fix.

**Comment by ashiksp** [comment]
Submitted Pull Request #264
