### ISSUE TITLE
Decide between cookie auth and token auth

### ISSUE THREAD

**Issue by vinay0x** [bigbinary/wheel#402]
Right now since the `sign_in` helper from `devise` is used, cookie-based authentication is also present in Wheel. Since we are moving to token auth, we could remove this helper and set `@current_user` manually in the `authenticate_user_using_x_auth_token` before action.

**Comment by sumanranjanpanda** [comment]
@yedhink _a Is it a valid issue now? Can you please verify and close it asap?
