### ISSUE TITLE
Temporary workaround for making yarn audit play nice with exit codes

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#434]
Yarn returns the summed up exit codes of each level as output. This may not play nice with jenkins and other tools, which expects either `0` for no error and `1` for error.

Yarn exit statuses:-
* 1 for INFO
* 2 for LOW
* 4 for MODERATE
* 8 for HIGH
* 16 for CRITICAL

The following is a workaround to make it  play atleast somewhat nice. I just conditionally check the exit status and see if it's greater than/equal to the LEVEL we explicitly provided. We can add the following to the `scripts` key in `package.json`:-
```json
"scripts": {
  "audit:exact": "audit() { cmd=\"yarn audit --groups dependencies \"$@\"\" /bin/bash -c  'command $cmd || exit_code=\"$?\" && ((\"$exit_code\" == \"${LEVEL:=8}\")) && exit 1 || exit 0'; }; audit",
  "audit:jenkins": "audit() { cmd=\"yarn audit --groups dependencies \"$@\"\" /bin/bash -c  'command $cmd || exit_code=\"$?\" && ((\"$exit_code\" >= \"${LEVEL:=8}\")) && exit 1 || exit 0'; }; audit",
},
```

### Usage
We have two options
- Return exit status `1` if severity level is exactly what we have explicitly provided through env variable `LEVEL` - use `yarn audit:exact`
- Or Return exit status `1` if severity level is greater than or equal to our `LEVEL`  - use `yarn audit:jenkins`

#### Only for Exact match
```bash
yarn audit:exact # by default level is high or 8
LEVEL="4" yarn audit:exact # only returns exit status 1 if yarn audit finds only moderate vulnerabilities
```

#### Greater or Equal Match - for Jenkins
If we want exit status `1` for all vulnerabilities greater than or equal to our `LEVEL`:-
```bash
yarn audit:jenkins # by default LEVEL is high or 8. Returns 1 if exit status >= LEVEL
LEVEL="4" yarn audit:jenkins # only returns exit status 1 if yarn audit finds vulnerabilities >= LEVEL
```

### To Be Noted
- Default value of `LEVEL` is `high` or `8` - so we can run without any args `yarn audit:jenkins` or `yarn audit:exact` 
- By default it `--groups dependencies`
- Accepts other args via command line
- Currently it prints packages of all vulnerabilities - haven't worked on fixing this. But we can pass the argument `--level <SEVERITY>` to make it print packages with vulnerability greater than or equal to this severity. It's the same arg that we pass to `yarn audit`. We can do `LEVEL=8 yarn audit:jenkins --level high`, which will return exit status `1` for all packages with severity >= 8 and will print grouped dependencies with level >= high.

### Examples
In this `wheel` repo, there is a single packge which is of `high` vulnerability.
#### Jenkins
** Exit Status 0 scenario**
![Screenshot_20201111_123011](https://user-images.githubusercontent.com/31244999/98779601-2432f100-241a-11eb-8496-44348e2cdcfe.png)

** Exit Status 1 scenario**
![Screenshot_20201111_123041](https://user-images.githubusercontent.com/31244999/98779626-2f861c80-241a-11eb-8312-79fb40b26b28.png)

#### Exact Match
** Exit Status 0 scenario**
![Screenshot_20201111_123240](https://user-images.githubusercontent.com/31244999/98779656-3dd43880-241a-11eb-9a81-a0d29379fc83.png)

** Exit Status 1 scenario**
![Screenshot_20201111_123207](https://user-images.githubusercontent.com/31244999/98779711-46c50a00-241a-11eb-9985-559c194c86f6.png)

@neerajdotname @chiraggshah 
It's not the best workaround for sure. But I think this would help with jenkins build for now! Let me know if this workaround should be added to wheel `package.json` too. Can make the PR.

**Comment by neerajdotname** [comment]
@yedhink Really nice work. 😍 . 

The PR is not needed for wheel because we don't currently run `yarn audit` as part of our CI run. We do run `bundle audit` though. However I'll take this workaround for the client work. Thanks.

**Comment by yedhink** [comment]
Sure :+1:  . Let's close this issue then.
