### ISSUE TITLE
Some of the packages in node and some gems are very outdated - might require upgrade

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#438]
I would say we take the upgradation process step by step in the node side. We could start with updating the `dev-dependencies` in package.json and then move to other ones if required. 

Similarly in the rails side, we could start updating the gems from `development` group first.

### Node Updations
![image](https://user-images.githubusercontent.com/31244999/99233096-cab33380-2818-11eb-9f4d-4c5be0a276cb.png)

### Rails Updations
```ruby
Outdated gems included in the bundle:
  * autoprefixer-rails (newest 10.0.2.0, installed 9.7.6, requested = 9.7.6) in group "default"
  * bootsnap (newest 1.5.1, installed 1.4.8) in group "default"
  * erubi (newest 1.10.0, installed 1.9.0)
  * font-awesome-sass (newest 5.15.1, installed 4.3.2.1, requested ~> 4.3.0) in group "default"
  * listen (newest 3.3.1, installed 3.2.1, requested ~> 3.2) in group "development"
  * mini_portile2 (newest 2.5.0, installed 2.4.0)
  * parallel (newest 1.20.0, installed 1.19.2)
  * parser (newest 2.7.2.0, installed 2.7.1.5)
  * puma (newest 5.0.4, installed 4.3.6, requested ~> 4.1) in group "default"
  * rubocop (newest 1.3.1, installed 0.82.0, requested ~> 0.82.0) in group "development"
  * rubocop-rails (newest 2.8.1, installed 2.6.0) in group "development"
  * simplecov (newest 0.19.1, installed 0.19.0) in group "test"
  * sprockets (newest 4.0.2, installed 3.7.2, requested ~> 3.7.2) in group "default"
  * tzinfo (newest 2.0.3, installed 1.2.7)
  * web-console (newest 4.1.0, installed 3.3.1, requested ~> 3.3.0) in group "development"
  * webpacker (newest 5.2.1, installed 4.3.0, requested ~> 4.0) in group "default"
  * zeitwerk (newest 2.4.1, installed 2.4.0)
```

@neerajdotname @vinay0x 
I can work on the PR for this. Can start with updating just the `dev-dependencies` in node side. Let me know your thoughts on this.

**Comment by neerajdotname** [comment]
@yedhink sure go ahead.  After sending the PR please wait until heroku app is built. Then login  into the heroku app and see if the page after login  comes up alright. That's it. After that PR can be merged.
