### ISSUE TITLE
switch to neeto repo for neeto-ui

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/wheel#441]
https://github.com/bigbinary/wheel/blob/master/package.json#L41

@edwinbbu _a

**Comment by neerajdotname** [comment]
@yedhink _a

**Comment by edwinbbu** [comment]
@neerajdotname For properly changing from nitro to neeto. We need to update all the reference in code. Hence the PR https://github.com/bigbinary/neeto-ui/pull/21 in neeto-ui needs to get merged. 

cc @neerajdotname @vinay0x @yedhink

**Comment by edwinbbu** [comment]
@edwinbbu _a I'll work on this since there are breaking changes to neetoui which needs to handled properly.

cc @vinay0x @yedhink
