### ISSUE TITLE
Switch from simple_form_for to Rails native form_for 

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/wheel#442]
https://monosnap.com/file/SIz7ju1SeGurOQQoTor8APbPuFYGNQ

- [ ] switch from `simple_form_for` to Rails native `form_for`
- [ ] Remove gem `simple_form_for`

**Comment by neerajdotname** [comment]
@yedhink _a

**Comment by yedhink** [comment]
@neerajdotname 
@vinay0x 

Just to clarify, do we actually need these files under the following `view` folders? It was my understanding that we have ported to react based views and every interaction is api based now. If that is the case, should we remove these folders/files/references to simple_form altogether?

- https://github.com/bigbinary/wheel/tree/b9e4bb34ad19c59ebfcc81f88c048bca82668b73/app/views/users
- https://github.com/bigbinary/wheel/tree/b9e4bb34ad19c59ebfcc81f88c048bca82668b73/app/views/shared
- https://github.com/bigbinary/wheel/tree/b9e4bb34ad19c59ebfcc81f88c048bca82668b73/app/views/pages
- https://github.com/bigbinary/wheel/tree/b9e4bb34ad19c59ebfcc81f88c048bca82668b73/app/views/mailer
- https://github.com/bigbinary/wheel/tree/0b5a9f00598700a712c4ad61f94937ea79c49538/config/locales
- https://github.com/bigbinary/wheel/blob/0b5a9f00598700a712c4ad61f94937ea79c49538/config/initializers/simple_form.rb
- https://github.com/bigbinary/wheel/blob/0b5a9f00598700a712c4ad61f94937ea79c49538/config/initializers/simple_form_bootstrap.rb

- `simple_form` references(i'm not sure what the / means here) like this etc: https://github.com/bigbinary/wheel/blob/878ce07198073698fd306bdaa94e47193873add6/app/javascript/src/components/Authentication/ResetPassword.jsx#L19


Let me know if we there is a use case for these files with our current api based architecture. If not, then I can work on removing the unwanted files/folders and references.

Thanks.

**Comment by vinay0x** [comment]
@yedhink Before removing those files, we have to make sure that everything has a React counterpart. As far as I know, we don't need `simple_form` or `form_for` helper anymore since we are using React entirely. But there are some views generated by Devise. You can remove those if we have the same functionalities in React. 

//cc @neerajdotname

**Comment by neerajdotname** [comment]
There are three places it is being used. https://monosnap.com/file/iosdUxRZXFugY6qym8GwihJiXCm2YZ

The other two places it is a an email. So we need `form_for`.

**Comment by vinay0x** [comment]
@neerajdotname Thanks 👍 

@yedhink Please go ahead with what Neeraj suggested.
