### ISSUE TITLE
jQuery in alert.js & dropdown.js

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/wheel#445]
jQuery is used in both https://github.com/bigbinary/wheel/blob/master/app/assets/javascripts/common/alerts.js and https://github.com/bigbinary/wheel/blob/master/app/assets/javascripts/common/dropdown.js. 

Is this still the best way to handle it given that all the views have moved to React.js.

@vinay0x _a

**Comment by vinay0x** [comment]
I don't think it's being used anywhere. We can remove these and remove jQuery altogether.

**Comment by neerajdotname** [comment]
@yedhink _a
