### ISSUE TITLE
Enforce proper naming of apis in front-end side

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#453]
Let's have a standard in place while writing apis in front-end side:

- All apis should reside in `apis/`
- Naming of api file = `pluralizedResourceName.js`. Eg:- `registrations.js`
- Naming of the api object = `pluralizedResourceNameApi`. Eg:- `registrationsApi`
- (Optional or Maximum try to) Try our best to name the actions within that api align with the actions associated with that `resource`. Eg:- `update, destroy, create` etc.
- Embed actions within api object for default named export

- Finally when exporting the object, it should be written like this:
```js
import axios from "axios";

const updatePassword = payload => axios.put("my/password/update", payload);

const registrationsApi = { // ----> Make sure to name this as the correct api name
  updatePassword, // ---> all actions as keys here
};

export default registrationsApi; // ---> export that api obj. Helps with auto-import in vscode
```

This convention would help with easier debugging and easier coding when someone new starts to write an api in front-end side. They only have to keep the `routes.rb` in mind. Rest they could just type without actually going into the apis folder and manually checking which file and object name should be used, because of the above mentioned conventions in place.

Ps:- Pluralisation can be based on whether it's `resource` or `resources` in routes.

I will work on this.
@yedhink _a

**Comment by vinay0x** [comment]
Existing APIs already in this format now. Just make the change for the new API added in #450

**Comment by yedhink** [comment]
@vinay0x 

I understand that. But since it was not exported as I had mentioned, there are differences in the existing codebase. Example:
- Should be `sessions.js`. 
- Should be `sessionsApi`
https://github.com/bigbinary/wheel/blob/3b985f83bcc81c648da66aeeca62360f6141b0ec/app/javascript/src/components/Authentication/Login.jsx#L7

- Should be `notesApi`. 
https://github.com/bigbinary/wheel/blob/b9e4bb34ad19c59ebfcc81f88c048bca82668b73/app/javascript/src/components/Dashboard/Notes/DeleteAlert.jsx#L3


I didn't want to pollute #450 with this pr changes. Thus a separate issue.

Let me know your thoughts.

**Comment by vinay0x** [comment]
@yedhink We can't enforce it completely. We can't name it sessions since it has signup API. Let it be authenticationAPI. It's more logically grouped.
