### ISSUE TITLE
Add dump.rdb to gitignore

### ISSUE THREAD

**Issue by philson-philip** [bigbinary/wheel#464]
@neerajdotname Can we add the `dump.rdb ` file to gitignore. So that we do not want to add it separately in all new projects.

**Comment by neerajdotname** [comment]
@philson-philip _a sure.

**Comment by philson-philip** [comment]
@yedhink _a Please add the `dump.rdb` file to `.gitignore`

**Comment by yedhink** [comment]
@philson-philip Please don't re-open issues that have already been closed by a PR. Open a new issue and link to this issue if need be.

Closing this issue.
