### ISSUE TITLE
Fix Password Reset Form

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/wheel#521]
Currently, it doesn't do anything. It should ideally trigger an email for password reset

**Comment by yedhink** [comment]
Fixed by https://github.com/bigbinary/wheel/pull/782

**Comment by yedhink** [comment]
My bad. Password change form is only completed. Email based `Forgot Password` or resetting is not yet completed. Reopening.

**Comment by sumanranjanpanda** [comment]
@yedhink _A Can you please verify and close it asap?
