### ISSUE TITLE
Update nodejs version across all neeto products

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#535]
From my understanding nodejs versions less than 16.xx are not natively supported in M1 Mac. Currently for M1 mac nodejs 14.xx can be installed via Rosetta. All nodejs 16.xx versions are natively supported in M1 chip.

Refer: https://github.com/nodejs/TSC/issues/886#issuecomment-824852839

The current version that we are using is 14.13.1, which doesn't show any LTS support in the official website either. But 14.17.3 is an active LTS(Fermium).

Refer: https://nodejs.org/en/download/releases/

@vinay0x

Should we upgrade all the node versions across all the neeto products as well as wheel to say either 14.17.3 or some version of 16.xx?

**Comment by vinay0x** [comment]
@yedhink Fair point. I think we can upgrade to 16. No point in staying well behind the latest. I'm guessing there are not many breaking changes and that the upgrade will be smooth.

**Comment by yedhink** [comment]
@amrutsabale _a

Please start by porting the node version in this repo. We will take up changing the node versions in other repos, iteratively.

Once you change the node version, please ensure that the application is working. Also please take a look at the docker script within `wheel`. If we need to update values in the script, then please take care of it.

You should also run the docker script to verify it's working after version update.

You can port node to `16.4.2`.

Let me know if you have any queries.

**Comment by amrutsabale** [comment]
@yedhink  previously, I had installed Nodejs `v14.17.1` on M1 mac via Rosetta. Should I install nodejs `16.4.2` via Rosetta or without Rosetta?
Because above you mentioned  that All nodejs 16.xx versions are natively supported in M1 chip.

**Comment by yedhink** [comment]
@amrutsabale We should try to install 16.xx without Rosetta.

**Comment by amrutsabale** [comment]
@yedhink  please go through this video.

[https://www.loom.com/share/a08b2c0bc0bd49c096089a80fcffd29b](https://www.loom.com/share/a08b2c0bc0bd49c096089a80fcffd29b)

links of the issue I faced while installing the wheel project after the latest node version update:
[ node-sass issue](https://github.com/nodejs/node/issues/38367)
[issue discussion](https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove)
Also, let me know, can I raise PR with these changes?

**Comment by amrutsabale** [comment]
I have one concern here. As node 16 support only node-sass version >=6.  If any package internally uses a lower node-sass version then it will not work properly with node 16.  I've mentioned in video that in `Wheel` project need to update `@rails/webpacker` package from  ` "@rails/webpacker": "5.2.1"` to `"@rails/webpacker": "^5.4.0"`.  

So If we are going with node 16, these types of changes we need to make in projects which are using packages dependent on `node-sass`.

**Comment by yedhink** [comment]
@amrutsabale

Thanks for the very detailed video. Much appreciated.

Can you confirm that you installed node v16.4.2 like mentioned in our [book](https://www.bigbinary.com/learn-rubyonrails-book/installing-ruby-on-rails#installing-a-node-version-using-nvm)?

If yes, then start by raising an issue in `granite` repo to update to new node version. You can assign it to yourself and take it up once you complete this wheel issue.

Also please mention the command you had used to update `webpacker` over here. This will help you when porting the content to our book.

**Comment by amrutsabale** [comment]
Yes, I had installed node v16.4.2 with `nvm` like mentioned in [book](https://www.bigbinary.com/learn-rubyonrails-book/installing-ruby-on-rails#installing-a-node-version-using-nvm).  

I will also raise an issue for the `granite` repo after this issue is fixed here in `wheel`.

The command I had used to update webpacker
`yarn add  @rails/webpacker `

**Comment by yedhink** [comment]
@amrutsabale _a

Command to upgrade `@rails/webpacker`, should be done using a specific version. Example: https://www.bigbinary.com/learn-rubyonrails-book/adding-tailwind#install-tailwindcss
