### ISSUE TITLE
Add neetoEditor to wheel

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/wheel#544]
We need to add neetoEditor to wheel so that it can be used as the reference for all the neeto products

<img width="1454" alt="Screenshot 2021-07-20 at 8 45 16 PM" src="https://user-images.githubusercontent.com/17916573/126424386-f0b5798b-2cdc-48b8-b794-5a9a77d46c1f.png">

@vinay0x _a, One of the issues I faced on setting up in neetoKB is that we need to exclude neeto-editor in nodeModuleLoader similar to react-table.

cc @sandip-mane

**Comment by vinay0x** [comment]
@edwinbbu _a Any idea why this needs to be done? For `react-table` too. It doesn't look like the cleanest approach on the first look.

**Comment by edwinbbu** [comment]
> @edwinbbu _a Any idea why this needs to be done? For `react-table` too. It doesn't look like the cleanest approach on the first look.

Yes. That's true. I'll take a look.
