### ISSUE TITLE
Quote $0 in githooks.

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/wheel#546]
Add quotes to command line argument $0 in pre-commit and pre-push hooks
https://github.com/bigbinary/wheel/blob/master/.husky/pre-commit#L2-L4

https://github.com/bigbinary/wheel/blob/master/.husky/pre-push#L2-L3

Expected way:
```bash
. "$(dirname "$0")/_/husky.sh"
```

If the parent folder contains spaces, the argument will split into two and `dirname` will get two arguments instead of one.

This won't be of much priority since here the parent folder is always `.husky`. But in case, this command is reused in some other folder containing spaces in its name, the command will fail.

**Comment by yedhink** [comment]
Closed via #548
