### ISSUE TITLE
Fix sidekiq initializer

### ISSUE THREAD

**Issue by josephv7** [bigbinary/wheel#552]
Shouldn’t the default value for `host` be `localhost` if no ENV variable is set? @sandip-mane

https://github.com/bigbinary/wheel/blob/f0a409c27b4f9282a5ef32ae45e319cfdfceffdf/config/initializers/sidekiq.rb#L10

https://github.com/bigbinary/wheel/blob/f0a409c27b4f9282a5ef32ae45e319cfdfceffdf/config/initializers/sidekiq.rb#L17

**Comment by sandip-mane** [comment]
I think we can follow how it's done in neetoDesk. We pass in the URL instead of passing host and port separately. Heroku too gives us the URL and not the host and port.

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] || 'redis://localhost:6379/1', size: 9 }
  schedule_file = "config/schedule.yml"

  if File.exists?(schedule_file)
    Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file)
  end
end
```

**Comment by yedhink** [comment]
@josephv7 _a

You can use the updated version which is presented in our learn-ror-book.

These are the major changes:
- Cron in dev env should have a different timing, such that we can test things without waiting too much.
- Cron jobs needn't be invoked in the test environment
- Moved URL's to secrets.yml

This is how the initializer with cron jobs inclusive would look like:
```ruby
# frozen_string_literal: true

if Rails.env.test? || Rails.env.heroku?
  require "sidekiq/testing"
  Sidekiq::Testing.inline!
end

Sidekiq::Extensions.enable_delay!

Sidekiq.configure_server do |config|
  config.redis = { url:  Rails.application.secrets.redis_url, size: 9 }
  unless Rails.env.test?
    schedule_file = "config/schedule.yml"

    if File.exists?(schedule_file)
      Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file)[Rails.env]
    end
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: Rails.application.secrets.redis_url, size: 1 }
end
```

And in secrets.yml:

```yaml
default: &default
  redis_url: <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
```

Currently, when updating the sidekiq initializer, I think you can avoid all cron job-related code. We don't use any cron jobs in wheel as far as I know.

cc: @sandip-mane Let me know if you have a difference of opinion. Thanks.

**Comment by yedhink** [comment]
@josephv7 Would you be able to please make a PR for this issue? Let's try to close this off since it's been open for like 16days.
