### ISSUE TITLE
move to db:prepare in setup task

### ISSUE THREAD

**Issue by haseebeqx** [bigbinary/wheel#554]
as per https://www.bigbinary.com/blog/rails-6-adds-rails-db-prepare-to-migrate-or-setup-a-database
```
rails db:create

# run the migrations
rails db:migrate

# prepopulate the database with initial/default data
rails db:seed  
```
can be replaced with  `rails db:prepare `

**Comment by sumanranjanpanda** [comment]
@yedhink _A The issue is created close to 2 years ago. Can you please verify whether we have already implemented it or not and close it asap?
