### ISSUE TITLE
Integrate prettier for ruby

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/wheel#558]
Can we try integrating prettier for ruby? 
https://github.com/prettier/plugin-ruby

@neerajdotname : Have we tried it before?

**Comment by neerajdotname** [comment]
@chiraggshah before putting it in wheel let's try it out in an internal project for a few months. If we still find it useful then we can add it to wheel.

**Comment by sumanranjanpanda** [comment]
@chiraggshah _a Can you post an update here?

cc: @yedhink
