### ISSUE TITLE
Something went wrong error message is displaying for invalid credentials

### ISSUE THREAD

**Issue by Prasannams97** [bigbinary/wheel#588]
https://loom.com/share/42d1cf9d867d45199d0a186fa1544b8b

**Comment by Prasannams97** [comment]
bug _t

**Comment by Prasannams97** [comment]
@yedhink _a

**Comment by Prasannams97** [comment]
@datt _a

**Comment by yedhink** [comment]
@edwinbbu _a

I think this might be an issue with neetoUI `Toastr` component.

I verified Rails side and it's working as intended.

`Toastr.error` is the one causing the issue in my research. I'm wondering if we are using an older version of `neetoui` in wheel.

Edwin please confirm if it's a version update issue or not. Thanks.
