### ISSUE TITLE
Disable certain rules in eslint

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#601]
- We should remove this rule. There are valid use cases that are shown as false positives now. Refer: https://github.com/yannickcr/eslint-plugin-react/issues/2584
```js
    "react/jsx-no-useless-fragment": ["error", { allowExpressions: true }],
```

**Comment by yedhink** [comment]
@sandip-mane 

Should we include Rails `migration` files in Rubocop formatting? The reason for asking is that some of the neeto products already have unformatted migration files. Thus if we apply formatting on them, then will there be any issues once we push to production? Will Heroku try to run those migrations again if we had modified them? 

If there are no issues let's keep the config as it's. Else we should ignore the `db/migrate` folder.

**Comment by sandip-mane** [comment]
> Should we include Rails migration files in Rubocop formatting?

Yes, we need to. `schema.rb` can be ignored but migrations need to be verified because these are not auto-generated. 

>  Will Heroku try to run those migrations again if we had modified them

No, rails won't re-run the migrations.
