### ISSUE TITLE
Should react/sort-prop-types be disabled?

### ISSUE THREAD

**Issue by karansapolia** [bigbinary/wheel#607]
As part of `eslint-plugin-react` we get the [`react/sort-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md) rule.

The issue is that this rule is not auto-fixable and its unclear how keeping each prop type declaration in alphabetical order helps us. Sorting propTypes for each file to get CircleCI builds to pass seems like an un-needed step, removing which does not affect code style or best practice. Let me know if this rule is useful, otherwise I suggest we disable it. 

@neerajdotname @yedhink  Let me know your thoughts on this.

**Comment by yedhink** [comment]
@karansapolia _a

I agree with your point. Personally don't think any eslint rule specific to `prop-types` needs to be enforced.

Can you please make a PR disabling this prop-type rule? Thanks.

**Comment by karansapolia** [comment]
@yedhink On further checking I noticed that you have already pushed [this commit](https://github.com/bigbinary/wheel/commit/a3510cae3d7bd150f112c519392bd4c4bd17e359#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5) and removed the `react/sort-prop-types` rule. I was using an earlier version of the eslint rules. 
Also as this rule is not enabled by default, I think we do not need to explicitly set it to a `off` state.
