### ISSUE TITLE
Also include .eslint-rules/custom.js in sync_with_wheel script

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/wheel#625]
Around here
https://github.com/bigbinary/wheel/blob/7f0240db22d1a1932981372335522957cdfb1b0d/.scripts/sync_with_wheel.sh#L24

@Amaljith-K _a
cc @yedhink

**Comment by yedhink** [comment]
@Amaljith-K Please don't add it.

**Comment by yedhink** [comment]
@Amaljith-K It was left out purposefully. NeetoCompliance directly uses the `sync_with_wheel` script to audit required configs. Thus if `custom.js` is present, then it would also check the diff which we don't want.

`custom.js` file can be added as an empty file with `.eslint-rules` for the time being.

I will raise an issue in `neetoCompliance` to not diff `eslint-rules/custom.js`. Then we can enforce it via sync_with_wheel itself.

**Comment by yedhink** [comment]
@Amaljith-K On second thoughts, we can't add `custom.js` to `sync_with_wheel`. `custom.js` in wheel is always empty. So when we run `sync_with_wheel`, if there are changes in `custom.js` within a project, then we don't want to overwrite it given that `custom` config within each project should be respected.

What we can do is add a verifier is neetoCompliance such that it will check for the existence of the `custom.js` file and if it's not present then ask the user to manually add an empty custom.js with the following content:
```js
module.exports = {};
```

**Comment by Amaljith-K** [comment]
@yedhink _a
Why not update the script in such a way that it will download the `./.eslint-rules/custom.js` file only if it doesn't already exist?

The one who makes integrates the `neeto-compliance` gem will anyway need to create `custom.js` since eslint will fail saying this:
```
ESLint couldn't find the config "./.eslint-rules/custom" to extend from. Please check that the name of the config is correct.
```
So there is not much gain in adding the same message into `neeto-compliance` gem.

**Comment by yedhink** [comment]
@unnitallman From my understanding neetoCompliance will diff all the files within the sync_with_wheel list.

What @Amaljith-K is suggesting can't be done directly in wheel alone. In neetoCompliance we would have to add a check to ensure that `custom.js` is NOT diffed.

Let me know your thoughts on this and what solution to go forward with. Please read previous comments on this issue to get more context.

Also go through: https://github.com/bigbinary/neeto_compliance/issues/3

**Comment by unnitallman** [comment]
> @yedhink _a
> Why not update the script in such a way that it will download the `./.eslint-rules/custom.js` file only if it doesn't already exist?
> 
> The one who makes integrates the `neeto-compliance` gem will anyway need to create `custom.js` since eslint will fail saying this:
> 
> ```
> ESLint couldn't find the config "./.eslint-rules/custom" to extend from. Please check that the name of the config is correct.
> ```
> 
> So there is not much gain in adding the same message into `neeto-compliance` gem.

@Amaljith-K @yedhink Don't add `custom.js` in wheel. Let the individual repos add it when Eslint asks them to.
