### ISSUE TITLE
Can we remove eslint rule `consistent-return`

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/wheel#632]
<img width="1761" alt="Screenshot 2021-09-29 at 1 50 22 PM" src="https://user-images.githubusercontent.com/17916573/135230996-37572d0d-6a84-4546-89ea-b39c54488939.png">

I have faced a similar issue in neetoInterview and now I can see the issue in neetoAuth PR https://github.com/bigbinary/neeto-auth-web/pull/623

Issue: 
When we are having a class method like `handleChange` or `handleSubmit`. It doesn't necessary have to return a value. But eslint is expecting a return value.

An empty return statement would resolve the eslint error. But it would dirty the code readablity.

@yedhink _a

cc @amaldinesh7

**Comment by yedhink** [comment]
@edwinbbu
I truly understand the concern here. But if we disable this rule then bad code practices will, again and again, get added to the codebase.

Example of a really unpredictable function declaration that will go through if we disabled `consistent-return` rule:
```js
function myFunc(item) {
  if (booleanCheck) { 
    return false;
  }
  // do something but not returning anything or returning void or anything but a boolean.
}
```

Let's say the above code gets committed to the codebase. After 6 months, a new developer joins and has to work on top of this. Let's say that I am the new developer.

Now questions arise if I see the above code within a codebase:
- What does this function actually return? Is it a boolean value? Is it predictable at all?
- How should other code which calls this function to be written? Should it check for `undefined` value too? Will that logic change if some other developers add another return statement within this function?

All the above questions would have been answered if there was consistent return statements.

I hope you get the gist of what I am trying to point out here.

Another example is people who do `Promise.reject` but don't return it.

I checked the code of that PR in neeto-auth. To fix the issue no need to add another `return;` statement. Just add return statements to either the `Toastr` calls or add a single return at the end which returns the variable `validationError` from the function named `upload`. [Refer to the code](https://github.com/bigbinary/neeto-auth-web/blob/dced78ca8cb71840645138288b110dabc8c1b960/app/javascript/src/components/Dashboard/Account/Profile/ProfileImage.js#L24-L41).

I think that the consistent-return rule for ESLint provides consistent returns on all of the JavaScript projects. It forces devs to consider all possible edge cases. This helps to cut down on potential sources of bugs and helps code to a more consistent and comprehensible design. 

**Reducing the chance for bugs or misunderstandings in our code is worth the small cost of explicitly adding a return statement.**

You can close this issue if you align with the idea and understood what I am trying to say here. If not, please feel free to let me know your thoughts.

**Comment by edwinbbu** [comment]
Point taken. I will also explore more on the same. Closing the issue.
