### ISSUE TITLE
Add curly braces if the flow/conditional statement is extended to a newline

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#633]
@yedhink _a

I have seen people write code like this, which is really hard to read and debug:
```
if (condition)
  perform_something --> visually this is confusing. Sometimes this line will be a big ramda chain.

else {
   something
 } 
```
https://eslint.org/docs/rules/curly#multi-or-nest

**Comment by edwinbbu** [comment]
@yedhink Agree with you. Having curly braces is cleaner 👍 .
