### ISSUE TITLE
Remove useless else statements

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#649]
```js
if (cond) {
  return value;
else { -------> unnecessary.
  return something_else;
}
```

- Prefer guard clauses
- We should our level best to avoid nesting

```js
     // auto-fixable: Remove the else part if or else-if chain has a return statement
    "no-else-return": "error",
```

**Comment by yedhink** [comment]
@edwinbbu Tagging you here so that you are aware of this new rule.

**Comment by edwinbbu** [comment]
@yedhink But removing else statements would affect the readability?

What happens when there is an `else if` condition. Would it uglify the code.

```
if {
...
} else if (condition) {
...
}
// here there would be no else condition
```

**Comment by yedhink** [comment]
@edwinbbu Please note that the statements within `if` or `else-if` should contain a `return` statement for this rule to be applied. Otherwise this rule won't get applied.

So the example you had pointed out would look something like so:
```js
if {
  return "from if";
} else if (condition) {
  return "from else-if";
}

return "independent of the above conditions. some people write this condition in else part, which is unnecessary.";
```

In the above case that I have shown, having this rule is the better option. Currently, we are only thinking of one single `return` statement within each clause.

But that needn't be the case in all codebases. People might write 10-15 lines of code within `if` statement and then do a return within. Thus if we add `else` clause unnecessarily, then it would lead to too much nesting and will affect readability.

This enforces the concept of guard-clauses to an extent.
