### ISSUE TITLE
The .byebug_history file is not tracked by .gitignore

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/wheel#655]
Using the `byebug` command for debugging generates a `.byebug_history` file listing all the debugging commands used. This file is not necessary and can be ignored.

**Comment by yedhink** [comment]
@AbhayVAshokan `pry` does most of the things that byebug does and is far more superior when to comes to extensibility and functionalities. Thus we can prefer `pry` over `byebug`.

Closing this issue.
