### ISSUE TITLE
React error when opening the site after force closing the browser

### ISSUE THREAD

**Issue by VarunSriram99** [bigbinary/wheel#680]
**Steps to recreate**

1. Open a browser and go to the wheel based site.
2. Login to the wheel site
3. Force close the browser(cmd+q in mac) without logging out.
4. Open the site again and it should technically still be logged in but some pages such as edit profile will result in react throwing an error like "cannot get email property of undefined".

**Cause**

The auth-token is validated via react when logging in but the context of ReactJS in wiped during force shutdown. So areas where `import {user} from useUserState` is used, will have the value of user as undefined.

**Possible fix**
Using localStorage to save the context data on login and retrieving data from the localStorage if the context is undefined is a possible fix.

**Code changes**
_app/javascript/src/contexts/user.js_
`const useUserState = () => {
  //const context = React.useContext(UserStateContext);
  let context = React.useContext(UserStateContext);
  if (context === undefined) {
    throw new Error("useUserState must be used within a UserProvider");
  }
  /************New code*******************/
  if (context.user) setToLocalStorage("context", JSON.stringify(context));
  else context = JSON.parse(getFromLocalStorage("context"));
  /********************************************/
  return context;
};`

_app/javascript/src/components/Common/Navbar/index.jsx_
`const handleLogout = async () => {
    try {
      setToLocalStorage("context", null); //Added line of code
      await authenticationApi.logout();
      authDispatch({ type: "LOGOUT" });
      resetAuthTokens();
      window.location.href = "/";
    } catch (error) {
      Toastr.error(error);
    }
  };`

**Comment by yedhink** [comment]
@VarunSriram99 Please format the code properly in your comment with proper syntax highlighting. https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by rishabhanand12** [comment]
> Hi Rishabh, If you see the video, u'll notice that the Avatar has changed. The issue I mentioned affects only the places where useUserContext is used. So if you try to open the edit profile page then you'll see a white screen.

@VarunSriram99 You are right. @yedhink Shall I take this up?

**Comment by yedhink** [comment]
Please test it in both chrome as well as safari. Also what happens when you refresh page?
