### ISSUE TITLE
VSCode settings causing error with rubocop extension

### ISSUE THREAD

**Issue by sreeram-venkitesh** [bigbinary/wheel#703]
The `misogi.ruby-rubocop` extension gives these errors when opening and saving ruby files. (Ruby version `3.0.2`)

```
command bundle exec rubocop returns empty output! please check configuration

-s/--stdin requires exactly one path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled (via eg. Include/Exclude), and so that certain cops like Naming/FileName can be checked.
```
The error is with the extension only and running `bundle exec rubocop` from the terminal works fine.

This can be resolved by removing `misogi.ruby-rubocop` as the default formatter for ruby files from `settings.json` in the `.vscode` directory and adding the necessary configs to format ruby files with the rubocop gem installed in the project.

@sreeram-venkitesh _a

**Comment by sreeram-venkitesh** [comment]
Shall I remove `misogi.ruby-rubocop` from the recommendations in `.vscode/extensions.json` as well?

CC: @yedhink

**Comment by yedhink** [comment]
>Shall I remove misogi.ruby-rubocop from the recommendations in .vscode/extensions.json as well?

@sreeram-venkitesh 

Please go ahead.
