### ISSUE TITLE
UI: Fix issue with delete button being clickable even when no selection is made 

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#709]
- Create 3 tasks
- Select the 2nd task and delete it
- After that the `Delete` button can again be clicked even when no selection/tasks have been checked.

Ideally `Delete` button should be disabled in this scenario too.

![image](https://user-images.githubusercontent.com/31244999/140051138-109b1bab-3901-4845-9813-79f0fdc15d9c.png)

**Comment by edwinbbu** [comment]
@edwinbbu _a
