### ISSUE TITLE
Improve way of managing null values in storage.js

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/wheel#719]
## setToLocalStorage

https://github.com/bigbinary/wheel/blob/ecfddd6aa16d2ae9ec78df160a4f0786f397de6d/app/javascript/src/helpers/storage.js#L1-L3
Should be replaced with:
```js
const setToLocalStorage = (key, value) => {
  if (value != null) {
    localStorage.setItem(key, JSON.stringify(value));
  } else localStorage.removeItem(key);
};
```
Reason: null values need not be saved. The key should be removed in such case.

## getFromLocalStorage

https://github.com/bigbinary/wheel/blob/ecfddd6aa16d2ae9ec78df160a4f0786f397de6d/app/javascript/src/helpers/storage.js#L5-L14
Should be replaced with:
```js
const getFromLocalStorage = key => JSON.parse(localStorage.getItem(key));
```
Reason: When the above change is made, this one-liner will perform the same way as the old one.
Edge cases: when no item exists in localStorage with given key, `localStorage.getItem(key)` retrieves `null`. `JSON.parse(null)` returns `null`

**Comment by yedhink** [comment]
@rishabhanand12 _a
Take a look into this.
