### ISSUE TITLE
Update `browserslist` package and add `eslint-config-prettier`

### ISSUE THREAD

**Issue by rishabhanand12** [bigbinary/wheel#743]
- [ ] Update `browserslist` using `npx browserslist@latest --updated-db`.
- [ ] Add the `eslint-config-prettier` package to turn off ESLint rules which raise a conflict with prettier. 

Prettier should be used for code formatting and ESlint should be used for ensuring code quality. We are using the `eslint-plugin-prettier` package to run prettier as an ESLint rule. This leads to a number of conflicts where ESLint rule disagrees with prettier. To avoid this we should use the `eslint-config-prettier` package which will disable the ESLint rules which conflict with Prettier. 

Ref - https://prettier.io/docs/en/integrating-with-linters.html 
         https://github.com/prettier/eslint-plugin-prettier#recommended-configuration

cc: @yedhink

**Comment by yedhink** [comment]
@rishabhanand12 _a

Sure you can take this up with high priority.
