### ISSUE TITLE
Upgrade to neetoUI v3

### ISSUE THREAD

**Issue by rishabhanand12** [bigbinary/wheel#759]
@rishabhanand12 _a

cc: @yedhink @karthiknmenon

**Comment by yedhink** [comment]
@karthiknmenon Are there any issues with migrating wheel to v3 at the moment? Is neetoUI v3 stable?

If it's stable, then we will take this up with priority.

**Comment by yedhink** [comment]
@rishabhanand12 _a

You can take this up.
