### ISSUE TITLE
Eslint error when using BigInt

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/wheel#760]
We have a use case for `BigInt` datatype in [neetoForm for storing number limits](https://github.com/bigbinary/neeto-form-web/pull/1891). However, when using BigInt, eslint is failing with the error `BigInt is not defined`. I believe this can be fixed by enabling es2020 globals.

Refer: https://futurestud.io/tutorials/eslint-how-to-fix-bigint-is-not-defined

**Comment by yedhink** [comment]
@rishabhanand12 _a

Take a look into this.

**Comment by yedhink** [comment]
@yedhink _a
