### ISSUE TITLE
Check what's the best way to deal with browser force quit and context not being set

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#774]
@Amaljith-K _a

Can you please take a look into this?

**Comment by yedhink** [comment]
Also refer: https://github.com/bigbinary/wheel/issues/680

**Comment by Amaljith-K** [comment]
The root cause of the issue: https://vimeo.com/671848521/98c153b856 (and possible solutions)
Reproduce the issue without force quitting: https://vimeo.com/671849073/e826edadea

**Comment by yedhink** [comment]
Upon further research I think the browser clearing the session-cookies on force quit might be the intended or accepted way of handling it and we should log the user out on such an event.

@Vishal24367 Can you actually put up a video similar to how we had debugged in neetoInvoice+Github? This will give more context.
