### ISSUE TITLE
Upgrade to Tailwind v3.0

### ISSUE THREAD

**Issue by rishimohan** [bigbinary/wheel#780]
This should be important since Tailwind v3 includes JIT mode that adds some great features like arbitrary values etc.

cc: @yedhink Since you're more aware of the state of wheel, do you think there's any blocker to this? I can take it up when I'm not working on any client project.

**Comment by sumanranjanpanda** [comment]
@yedhink _a Can you please verify whether we are already using it or not? Please check with @praveen-murali-ind on neetoUI.

**Comment by yedhink** [comment]
As far as I know Tailwind is not widely used anymore in neetoUI. Thus this issue may not be worth pursuing anymore. @praveen-murali-ind Please reopen if this upgrade is necessary.
