### ISSUE TITLE
Upgrade to Rails 7

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#783]
@yedhink _a

**Comment by neerajdotname** [comment]
Let's remove ActiveAdmin permanently from wheel.

**Comment by yedhink** [comment]
>Let's remove ActiveAdmin permanently from wheel.

Yes. Have done it in #784.

**Comment by abrahamparayil** [comment]
@yedhink 
I was looking at what would be the amount of work needed to migrate neetoForm from Rails 6 to Rails 7 (for fun) and I saw a few issues open for Rails 7 that might break the functionality for some features used in neetoForm. Listing them below.
- https://github.com/rails/rails/issues/45267
- https://github.com/rails/rails/issues/45056
- https://github.com/rails/rails/issues/44986

**Comment by sumanranjanpanda** [comment]
@yedhink any update on this?

**Comment by yedhink** [comment]
This is already done.
