### ISSUE TITLE
Research on ways to handle env variables for production env in secrets.yml

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#787]
@yedhink _a

**Comment by yedhink** [comment]
- [ ] Try to split up secrets.yml into multiple files
```
secrets.yml - parent
secrets.app.yml - child
```
- [ ] Remove defaults and move them to .env.devlopment

**Comment by neerajdotname** [comment]
@yedhink https://www.loom.com/share/48ef37f9cb7342dd9096c78b36b2ccbf

**Comment by yedhink** [comment]
@neerajdotname Thanks for pointing that out. It's a valid point. 

So in the call with Unni, we thought about a better way to document/add comments in secrets.yml and how to delegate that job to the neetoCompliance as well as the project team. Currently the secrets.yml is a mixup of all different kinds of keys, inclusive of keys which are common to all neeto apps, neetoSSO keys, AWS keys, etc and the app specific keys.

- The app specific keys - these are the keys which can be best documented by the tech lead or someone working on the project itself
- Common keys - can be documented by neetoCompliance because it's common to all neeto repos

So let's consider the case of documenting the common keys. In this case going to each project and updating secrets.yml and the common keys with appropriate comments might be a hectic and time consuming job. Rather, if there is a file called `secrets.common.yml`, then neetoCompliance can ensure that all projects use the same file content easily.

**But, on second thoughts, I believe we can handle all these cases in secrets.yml itself by adding appropriate parent keys. Will work on it and update.**

cc: @unnitallman
