### ISSUE TITLE
Add eslint configuration for arrow function body styling

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/wheel#792]
Reference: https://eslint.org/docs/rules/arrow-body-style
Let us use `as-needed` configuration. 

It will correct this code:
```js
  const getDiscountDescription = data => {
    return `${getEntitledProducts(data)} · ${getMinimumRequirements(data)}`;
  };
```
to this:
```js
  const getDiscountDescription = data => 
    `${getEntitledProducts(data)} · ${getMinimumRequirements(data)}`;
```

Similarly:
```jsx
<div>
  {something.map(item => {
    return (
      <Button key={item.id} />
    )
  })}
</div>
```
to:
```jsx
<div>
  {something.map(item => <Button key={item.id} />)}
</div>
```

Which is more concise.

**Comment by Amaljith-K** [comment]
Also, an unrelated configuration that we could include in the same PR: 
https://eslint.org/docs/rules/prefer-template

**Comment by yedhink** [comment]
@yedhink _a

**Comment by yedhink** [comment]
Also add https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md
