### ISSUE TITLE
Moving away from Ramda

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#816]
Discussion context: https://github.com/bigbinary/neeto-store-web/pull/385#discussion_r844711884
<img width="779" alt="image" src="https://user-images.githubusercontent.com/31244999/162130310-f220d02f-8b58-4987-b8e1-bffb154fa723.png">

------

@neerajdotname Figured we should move the discussion here as `wheel` itself uses Ramda. But we can definitely change all Ramda logic in wheel to vanilla JS itself without any issues.

Lemme know your thoughts on this.

@chiraggshah Can you also share your thoughts on this? Thanks.

**Comment by neerajdotname** [comment]
@yedhink I agree 100%. Let's do it.

**Comment by chiraggshah** [comment]
Agree. 👍
