### ISSUE TITLE
Replace Ramda with lodash

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/wheel#821]
Replace `isEmpty` and `isPresent` functions with equivalent code from lodash. There is no upside of rebuilding such utility functions which are already present in lodash. Open to using https://github.com/lodash/lodash/wiki/FP-Guide if it helps in any way. 

@yedhink _a

**Comment by neerajdotname** [comment]
Ref https://github.com/bigbinary/wheel/commit/57ceb693b77d655cb2379ed1639a988405ac9b8c

**Comment by yedhink** [comment]
@neerajdotname Please watch and lemme know your thoughts: https://www.loom.com/share/208089e9fc4c4c029d0b8d24bf8663f2

**Comment by neerajdotname** [comment]
@yedhink https://www.loom.com/share/e171436deef0411c89bb8fe4bd2c9d48
