### ISSUE TITLE
Fix frontend console error

### ISSUE THREAD

**Issue by Prasannams97** [bigbinary/wheel#834]
<img width="1311" alt="Screenshot 2022-04-26 at 2 10 44 PM" src="https://user-images.githubusercontent.com/75472228/165259773-3024af6b-a1d3-4698-864e-1b453aef74d0.png">

**Comment by Prasannams97** [comment]
console-error _t

**Comment by sumanranjanpanda** [comment]
@yedhink _a Can you please verify this issue whether it's still there or not?
