### ISSUE TITLE
Specifying gem version in Gemfile with twiddle-waka

### ISSUE THREAD

**Issue by rtdp** [bigbinary/wheel#87]
I started one of demo project from wheel. As I have simple_form 1.4.1 and 3.1.0 both present on machine, running `bundle` choose to go with 1.4.1 version of simple_form.

App fails to boot because it depends on 3.1.0 APIs of gem.

So, can we have versions specified for all the gems that we have in Gemfile and also make sure we have this as style guideline. I wrote something about it long back here - http://rtdptech.com/2011/09/specifying-gem-versions-in-gemfile-for-rails-application/

**Comment by vipulnsward** [comment]
simple_form is locked at 3.1.0 here -  https://github.com/bigbinary/wheel/blob/master/Gemfile.lock#L254
bundle still picked up 1.4.1.?

**Comment by rtdp** [comment]
@vipulnsward I had changed rails version and then ran `bundle update` afterwards instead of `bundle update rails`
