### ISSUE TITLE
Update `getFromLocalStorage` utils function to handle error

### ISSUE THREAD

**Issue by udai1931** [bigbinary/wheel#876]
Update the `getFromLocalStorage` function to use try-catch block. So that if some non-parseable value is defined in local storage then it can be caught and an empty string can be returned in that case.
cc: @yedhink

**Comment by yedhink** [comment]
@udai1931 _a

**Comment by udai1931** [comment]
> Make sure to fix the issues in the authenticable concern as we had discussed

I checked and in wheel is already updated.
