### ISSUE TITLE
Add TypeScript declarations to avoid unnecessary errors from VSCode

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#889]
@yedhink _a

**Comment by udai1931** [comment]
@yedhink Getting these warning in console after above PR.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43845165/190423355-660e4fea-6ddc-4c73-b203-033b9d72e0ee.png">

**Comment by yedhink** [comment]
@udai1931 Can you please put up a video showing when exactly you are getting these warnings?

**Comment by yedhink** [comment]
@udai1931 Thanks for pointing this out. I have fixed the issue in https://github.com/bigbinary/wheel/pull/893. Please rebase and see if that fixes the issue for you.
