### ISSUE TITLE
Disallow implicit coercion

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#900]
I believe this would make the code more readable. In the `allow` list we can add coercion operators that we need to keep, if any. I would go with disallowing all of them as mentioned in below rule.

@Amaljith-K Can you please share your thoughts regarding this rule?

https://eslint.org/docs/latest/rules/no-implicit-coercion

**Comment by Amaljith-K** [comment]
We should be allowing `!!foo`. It is very frequently used in neeto world & is more convenient than `Boolean(foo)`.
We can disable the rest of all kinds of conversions.

**Comment by yedhink** [comment]
>We should be allowing !!foo. It is very frequently used in neeto world & is more convenient than Boolean(foo).
We can disable the rest of all kinds of conversions.

Done exactly that. 👍
