### ISSUE TITLE
Recommend new extensions for VSCode

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#920]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/31244999/197766181-d4dba1b6-1716-4193-b3de-06c534f8c06a.png">

Although in the book we are asking to install Prettier separately, the Prettier extension is ignored on purpose in Wheel. Have faced a lot of false positives when combined with ESLint. A beginner might go down the rabbit hole of trying to fix the `red squiggly` lines that the Prettier extension throws, which might be a false positive. Source of truth should be the command line and all prettier formatting will be done either ways via Git hooks.

@udai1931 _a Add these extensions to https://github.com/bigbinary/wheel/blob/main/.vscode/extensions.json

**Comment by neerajdotname** [comment]
@yedhink My thoughts on this and more https://www.loom.com/share/481a1cc9f6744107a32a84598655df82

**Comment by yedhink** [comment]
Got the issue. Will be taken care of in https://github.com/bigbinary/bigbinary-website/issues/2520
