### ISSUE TITLE
Fix husky pre-commit error

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/wheel#928]
Husky pre-commit hook raises an error as shown below when files contain the `"======="` pattern. Please find the images below for more information about this issue: 

`Error`
![Husky error](https://user-images.githubusercontent.com/35305344/205222840-47d948e3-87ba-4a25-8798-eaa5df95c3a7.png)

`prevent_pushing_to_main.sh`
![prevent-pushing-to-main sh](https://user-images.githubusercontent.com/35305344/205227159-1c6265a8-a0ca-4c52-8b7c-88d37c4b99e1.png)

`rubocop.yml`
![rubocop yml](https://user-images.githubusercontent.com/35305344/205227157-1ecb3666-d258-4aa2-b6b9-28319b76f724.png) 

@yedhink

**Comment by udai1931** [comment]
@yedhink I can reproduce the same, if we clone the `wheel`, delete `.git`, `setup husky` and then commit the code, same error occurs.
