### ISSUE TITLE
Disallow methods with `is_` prefix if it already contains a `?` as suffix

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#951]
https://github.com/rubocop/rubocop/blob/master/config/default.yml#L2857

**Comment by sumanranjanpanda** [comment]
@yedhink _a Any update on this?

If we are not going to work on it immediately, let's close and move issues to the neetoWheel Roadmap project in neetoPlanner. We will create a new issue once someone is available to work on it.

**Comment by yedhink** [comment]
Moved to planner.
