### ISSUE TITLE
Warn about unnecessarily snake_cased variables

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#953]
https://eslint.org/docs/latest/rules/camelcase

**Comment by sumanranjanpanda** [comment]
@yedhink _a Any update on this?

If we are not going to work on it immediately, let's close and move issues to the neetoWheel Roadmap project in neetoPlanner. We will create a new issue once someone is available to work on it.

**Comment by yedhink** [comment]
Moved to planner.
