### ISSUE TITLE
Update node version to 18.12

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/wheel#957]
1. Update node version to 18.12 similar to other neeto products. This is necessary to make the corresponding changes in neetoIcons, neetoUI, and neetoEditor packages.
2. Update the `.browserslist` file to be similar to https://github.com/bigbinary/neeto-desk-web/blob/main/.browserslistrc. Both neetoUI and neetoEditor has some feature that won't be supported in some older browsers.

@yedhink _a can you please assign one person to work on this issue?

**Comment by yedhink** [comment]
@navaneethsdk _a Please take this up. If you need more clarifications regarding this issue, then please contact Abhay.

Right now I would say this is lower priority compared to the priority issues in the book. But get on a call with Abhay and see how soon this issue should be fixed. If this is very high priority, then you can pause the other work and take this up.

**Comment by sumanranjanpanda** [comment]
@navaneethsdk  Any update on this?

**Comment by yedhink** [comment]
@sumanranjanpanda This will take some more time. Right now Navaneeth is assigned some high priority issues with orientation and content. I will take a look into this.

**Comment by sumanranjanpanda** [comment]
@yedhink  Can we move this to neetoPlanner project roadmap? We can create a new issue, once @navaneethsdk is available.

**Comment by yedhink** [comment]
@sumanranjanpanda I will be looking into this this week.
