### ISSUE TITLE
Move wheel-production from heroku to neeto-deploy

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/wheel#965]
https://monosnap.com/file/ALAKCTCiaxbqRZV1MoSmLAhkpRtHy0

@yedhink _a

**Comment by sumanranjanpanda** [comment]
@yedhink Are we on it?

**Comment by yedhink** [comment]
This is already done. Have to update the Readme. Will take care of this ASAP.

https://wheel-production.neetoreviewapp.net/
