### ISSUE TITLE
Multiple react entry point

### ISSUE THREAD

**Issue by sritabh** [bigbinary/wheel#990]
There are more than one entry point for react components, which forces components to render twice.

First entry point
https://github.com/bigbinary/wheel/blob/b980f3a25eed41f64da8cf0626fb87e5ce7031ba/app/views/home/index.html.erb#L1

Second entry point
https://github.com/bigbinary/wheel/blob/b980f3a25eed41f64da8cf0626fb87e5ce7031ba/app/javascript/packs/application.js#L20

Possible fix could be to remove second entry point.

**Comment by yedhink** [comment]
The`mountComponents()` function call is actually added to ensure that the components show up in React dev tools etc. I don't think we need to remove this call.

@Amaljith-K We are using the piece of code in neeto too: https://github.com/bigbinary/neeto-wheel-web/blob/main/app/javascript/packs/application.js#L21C1-L21C33. Have you experienced any double rendering issues as mentioned in the issue in neeto?

**Comment by Amaljith-K** [comment]
I haven't noticed the problem. I'll check again and will update.

**Comment by yedhink** [comment]
@Amaljith-K I thought that statement was needed to make React dev tools work. If it's not needed anymore with Shackapacker then I guess we can remove that statement.

**Comment by Amaljith-K** [comment]
Everything works fine without that statement.
@ajmaln please make necessary changes in neeto products too.
